### PR TITLE
Add Charmhub proxy documentation.

### PR DESCRIPTION
**Pull request by milos-lukic**
This MP adds an offline Charmhub section which covers the whole flow for exporting and importing charms into an offline (airgap) instance of Snap store proxy.

Part of: https://warthogs.atlassian.net/browse/SN-2445

The added how-to covers:
- Scope of the offline Charmhub
- Configuration of the offline Charmhub
- Exporting charms from SaaS Charmhub
- Importing charms to local instance
- Setting up Juju  use the local instance

The export section is only partially covered, Bowen will probably make some more additions to it in a separate MP.

### CODE REVIEW

**Comment by milos-lukic** [comment]
Changed to WIP so Bowen's additions can be merged and incorporated first.

**Review by bowenfan96 — APPROVED** [review]
LGTM, thanks!

**Comment by milos-lukic** [comment]
@bowenfan96 I rebased the changes on top of your PR - I used the title "Offline Charmhub" so it's consistent with the existing "Offline Store" and to avoid any ambiguity with online mode.

**Comment by bowenfan96** [comment]
Thank you, looks great to me! I don't have write access to this repo so we'd need to ask Przemek or David or Anton to merge, I think.

**Pull request merged**
